# [LAB-03] Pandas

## 3. DataFrame 자료형

### #01 준비작업

1. 라이브러리 참조

In [1]:
from pandas import DataFrame, read_csv, read_excel

### #02 DataFrame 생성하기

1. 2차원 리스트를 DataFrame으로 변환

In [2]:
# 어느 학급의 성적을 표현한 2차원 리스트
grade_data = [
                [1, "남자", 98, 77, 88, 64],
                [2, "여자", 88, 90, 62, 72],
                [1, "남자", 92, 70, 83, 79],
                [3, "여자", 63, 60, 31, 70],
                [4, "남자", 75, 50, 90, 88]
            ]

# 2차원 리스트를 데이터프레임으로 변환
# -> 학생별 점수 표현
df = DataFrame(grade_data)
df

   0   1   2   3   4   5
0  1  남자  98  77  88  64
1  2  여자  88  90  62  72
2  1  남자  92  70  83  79
3  3  여자  63  60  31  70
4  4  남자  75  50  90  88

2. 인덱스와 컬럼 이름 지정하기

In [3]:
# 인덱스 이름으로 사용할 리스트
i_names = ['철수', '영희', '민철', '수현', '호영']

# 컬럼 이름으로 사용할 리스트
c_names = ['학년', '성별', '국어', '영어', '수학', '과학']

# 인덱스와 컬럼이름 지정하기
df = DataFrame(grade_data, index=i_names, columns=c_names)
df

    학년  성별  국어  영어  수학  과학
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

3. 리스트를 원소로 갖는 딕셔너리로 DataFrame 생성

In [4]:
# 어느 학급의 성적표를 표현한 딕셔너리
grade_dic = {
    '학년': [1, 2, 1, 3, 4],
    '성별': ['남자', '여자', '남자', '여자', '남자'],
    '국어': [98, 88, 92, 63, 75],
    '영어': [77, 90, 70, 60, 50],
    '수학': [88, 62, 83, 31, 90],
    '과학': [64, 72, 79, 70, 88]
}

# 딕셔너리 key가 컬럼(열)이름이 된다.
df = DataFrame(grade_dic)
df

   학년  성별  국어  영어  수학  과학
0   1  남자  98  77  88  64
1   2  여자  88  90  62  72
2   1  남자  92  70  83  79
3   3  여자  63  60  31  70
4   4  남자  75  50  90  88

4. 인덱스와 인덱스 이름과 제목을 지정한 DataFrame

In [5]:
# 인덱스 지정하기
df = DataFrame(grade_dic,
               index=['철수', '영희', '민철', '수현', '호영'])

# 인덱스 제목 지정하기
df.index.name = '이름'
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

5. 딕셔너리를 원소로 갖는 리스트를 활용한 DataFrame 생성

In [6]:
grade_list = [
    {"이름": "철수", "학년": 1, "성별": "남자", "국어": 98, "영어": 77,
     "수학": 88, "과학": 64},
    {"이름": "영희", "학년": 2, "성별": "여자", "국어": 88, "영어": 90,
     "수학": 62, "과학": 72},
    {"이름": "민철", "학년": 1, "성별": "남자", "국어": 92, "영어": 70,
     "수학": 83, "과학": 79},
    {"이름": "수현", "학년": 3, "성별": "여자", "국어": 63, "영어": 60,
     "수학": 31, "과학": 70},
    {"이름": "호영", "학년": 4, "성별": "남자", "국어": 75, "영어": 50,
     "수학": 90, "과학": 88}
]

df = DataFrame(grade_list)
df

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

### #03 인덱스 다루기

1. 이미 생성된 DataFrame의 특정 컬럼을 index로 지정하기

In [7]:
df2 = df.set_index('이름')
df2

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

2. inplace = True: 복사본을 생성하지 않고 원본에 즉시 반영하기

In [8]:
df.set_index('이름', inplace=True)
df

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
영희   2  여자  88  90  62  72
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  70
호영   4  남자  75  50  90  88

3. 인덱스 해제하기

In [9]:
df3 = df.reset_index()
df3

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

4. reset_index() 사용 시 주의사항

In [13]:
df3.reset_index()

   index  이름  학년  성별  국어  영어  수학  과학
0      0  철수   1  남자  98  77  88  64
1      1  영희   2  여자  88  90  62  72
2      2  민철   1  남자  92  70  83  79
3      3  수현   3  여자  63  60  31  70
4      4  호영   4  남자  75  50  90  88

5. 인덱스를 해제하면서 기존 인덱스 제거하기

In [14]:
df3.reset_index(drop=True)

   이름  학년  성별  국어  영어  수학  과학
0  철수   1  남자  98  77  88  64
1  영희   2  여자  88  90  62  72
2  민철   1  남자  92  70  83  79
3  수현   3  여자  63  60  31  70
4  호영   4  남자  75  50  90  88

### #04 외부 파일로부터 DataFrame 생성

1. CSV 파일을 DataFrame으로 가져오기

In [15]:
df = read_csv("https://data.juyounga.kr/data/grade.csv",
              encoding="euc-kr")
df

   이름  학년  성별  국어   영어  수학  과학
0  철수   1  남자  98   77  88  64
1  영희   2  여자  88  120  62  72
2  민철   1  남자  92   70  83  79
3  수현   3  여자  63   60  31  71
4  호영   4  남자  75   50  90  88
5  영호   4  남자  80   88  91  72
6  용식   2  남자  82   88  79  90
7  나영   1  여자  90   92  81  95
8  석영   1  남자  91   90  89  80

2. 인덱스로 사용할 열의 이름 지정하기

In [16]:
df = read_csv("https://data.juyounga.kr/data/grade.csv",
              encoding="euc-kr",
              index_col='이름')
df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

3. 엑셀 파일 처리를 위한 패키지 설치

In [17]:
!pip install --upgrade openpyxl xlrd

Requirement already satisfied: openpyxl in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: xlrd in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.2)
Requirement already satisfied: et-xmlfile in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)

4. 엑셀 파일로부터 가져오기

In [20]:
df = read_excel("https://data.juyounga.kr/data/grade.xlsx",
              index_col='이름')
df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80