# [LAB-03] Pandas

## 4. 데이터 확인하기

### #01 준비작업

1. 라이브러리 설치

In [6]:
!pip install --upgrade jussam libpysal esda

Requirement already satisfied: jussam in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.5.21)
Requirement already satisfied: libpysal in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.15.0)
Collecting esda
  Downloading esda-2.10.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: jupyter in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.1.1)
Requirement already satisfied: tqdm in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (4.70.1)
Requirement already satisfied: pyarrow in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (25.0.1)
Requirement already satisfied: fastparquet in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (2026.9.0)
Requirement already satisfied: tabulate in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.10.0)
Requirement already satisfied: numpy in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (2.5.3)
Requirement already satisfied: pandas in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (3.0.6)
Requirement already satisfied: scipy in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.18.1)
Requirement already satisfied: joblib in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.6.0)
Requirement already satisfied: scikit-learn in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.9.1)
Requirement already satisfied: statsmodels in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.15.0)
Requirement already satisfied: requests in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (2.34.2)
Requirement already satisfied: cloudpickle in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (3.1.2)
Requirement already satisfied: psutil in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from jussam) (7.2.2)
Requirement already satisfied: importlib_metadata in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (9.0.1)
Requirement already satisfied: deprecation in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (2.1.0)
Requirement already satisfied: xxhash in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (4.0.1)
Requirement already satisfied: matplotlib in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (3.11.2)
Requirement already satisfied: seaborn in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.13.2)
Requirement already satisfied: plotly in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (7.1.0)
Requirement already satisfied: kaleido in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.4.0)
Requirement already satisfied: openpyxl in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (3.1.5)
Requirement already satisfied: xlrd in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (2.0.2)
Requirement already satisfied: lxml in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (6.1.3)
Requirement already satisfied: bs4 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.0.2)
Requirement already satisfied: pingouin in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.7.0)
Requirement already satisfied: statannotations in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.7.2)
Requirement already satisfied: xgboost in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (3.4.1)
Requirement already satisfied: lightgbm in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (4.7.0)
Requirement already satisfied: catboost in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.2.10)
Requirement already satisfied: shap in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.52.0)
Requirement already satisfied: pmdarima in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (2.1.1)
Requirement already satisfied: prophet in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.4.0)
Requirement already satisfied: imbalanced-learn in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.14.2)
Requirement already satisfied: category-encoders in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (2.11.1)
Requirement already satisfied: yellowbrick in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.5)
Requirement already satisfied: geopandas in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (1.1.4)
Requirement already satisfied: kmodes in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.12.2)
Requirement already satisfied: jenkspy in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.4.1)
Requirement already satisfied: kneed in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jussam) (0.8.6)
Requirement already satisfied: beautifulsoup4>=4.13.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from libpysal) (4.15.0)
Requirement already satisfied: jinja2 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from libpysal) (3.1.6)
Requirement already satisfied: packaging>=24.1 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from libpysal) (26.3)
Requirement already satisfied: platformdirs>=4.3 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from libpysal) (4.11.8)
Requirement already satisfied: shapely>=2.1 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from libpysal) (2.1.2)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4>=4.13.0->libpysal) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from beautifulsoup4>=4.13.0->libpysal) (4.16.0)
Requirement already satisfied: pyogrio>=0.7.2 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from geopandas->jussam) (0.13.0)
Requirement already satisfied: pyproj>=3.5.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from geopandas->jussam) (3.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from pandas->jussam) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->jussam) (2026.4)
Requirement already satisfied: certifi in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pyogrio>=0.7.2->geopandas->jussam) (2026.7.22)
Requirement already satisfied: six>=1.5 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas->jussam) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->jussam) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->jussam) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->jussam) (2.8.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn->jussam) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn->jussam) (3.7.0)
Requirement already satisfied: graphviz in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from catboost->jussam) (0.21)
Requirement already satisfied: cramjam>=2.3 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fastparquet->jussam) (2.12.1)
Requirement already satisfied: fsspec in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fastparquet->jussam) (2026.9.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imbalanced-learn->jussam) (0.1.6)
Requirement already satisfied: zipp>=3.20 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from importlib_metadata->jussam) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->libpysal) (3.0.3)
Requirement already satisfied: notebook in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter->jussam) (7.6.3)
Requirement already satisfied: jupyter-console in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter->jussam) (6.6.3)
Requirement already satisfied: nbconvert in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter->jussam) (7.17.1)
Requirement already satisfied: ipykernel in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from jupyter->jussam) (7.3.0)
Requirement already satisfied: ipywidgets in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter->jussam) (8.1.9)
Requirement already satisfied: jupyterlab in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter->jussam) (4.6.4)
Requirement already satisfied: comm>=0.1.1 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (9.17.1)
Requirement already satisfied: jupyter-client>=8.9.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (8.10.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (1.7.2)
Requirement already satisfied: pyzmq>=25 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (27.2.0)
Requirement already satisfied: tornado>=6.4.1 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (6.5.8)
Requirement already satisfied: traitlets>=5.4.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipykernel->jupyter->jussam) (5.16.1)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter->jussam) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter->jussam) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter->jussam) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter->jussam) (3.0.53)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter->jussam) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter->jussam) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter->jussam) (0.8.3)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->jupyter->jussam) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter->jussam) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter->jussam) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\itwill\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter->jussam) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.16 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets->jupyter->jussam) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipywidgets->jupyter->jussam) (3.0.17)
Requirement already satisfied: async-lru>=1.0.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab->jupyter->jussam) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab->jupyter->jussam) (0.28.1)
Requirement already satisfied: jupyter-builder>=1.0.2 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab->jupyter->jussam) (1.2.3)
Requirement already satisfied: jupyter-lsp>=2.0.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab->jupyter->jussam) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab->jupyter->jussam) (2.21.1)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab->jupyter->jussam) (2.28.1)
Requirement already satisfied: notebook-shim>=0.2 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab->jupyter->jussam) (0.2.4)
Requirement already satisfied: anyio in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->jussam) (4.15.1)
Requirement already satisfied: httpcore==1.* in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->jussam) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter->jussam) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (5.11.1)
Requirement already satisfied: prometheus-client>=0.9 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (0.26.0)
Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (3.0.5)
Requirement already satisfied: send2trash>=1.8.2 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (1.9.2)
Requirement already satisfied: babel>=2.10 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->jussam) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->jussam) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->jussam) (4.26.0)
Requirement already satisfied: argon2-cffi-bindings in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (26.1.0)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->jussam) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->jussam) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->jussam) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->jussam) (2026.6.3)
Requirement already satisfied: python-json-logger>=2.0.4 in C:\Users\itwill\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter->jussam) (4.2.0)

2. 라이브러리 참조

In [7]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/
🔖 Version: 0.5.21

3. 가상의 과목별 점수 데이터 불러오기

In [8]:
origin = load_data('GRADE')
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### #02 데이터 구조 확인

1. 데이터의 차원과 크기

In [9]:
print("차원:", origin.ndim)
print("크기:", origin.shape)

차원: 2
크기: (9, 6)

2. 각 변수의 데이터 타입 확인

In [10]:
origin.dtypes

학년    int64
성별      str
국어    int64
영어    int64
수학    int64
과학    int64
dtype: object

3. 각 필드별 정보 확인

In [11]:
origin.info()

<class 'pandas.DataFrame'>
Index: 9 entries, 철수 to 석영
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      9 non-null      int64
 1   성별      9 non-null      str
 2   국어      9 non-null      int64
 3   영어      9 non-null      int64
 4   수학      9 non-null      int64
 5   과학      9 non-null      int64
dtypes: int64(5), str(1)
memory usage: 612.0 bytes

### #03 데이터 내용 확인

1. 특정 "열"의 데이터 확인

In [12]:
origin['국어']

이름
철수    98
영희    88
민철    92
수현    63
호영    75
영호    80
용식    82
나영    90
석영    91
Name: 국어, dtype: int64

2. 특정 "열"의 타입 확인 -> Series

In [13]:
type(origin['국어'])

pandas.Series

3. 원하는 열만 추출하기

In [14]:
df2 = origin[['국어', '영어', '수학']]
df2

    국어   영어  수학
이름
철수  98   77  88
영희  88  120  62
민철  92   70  83
수현  63   60  31
호영  75   50  90
영호  80   88  91
용식  82   88  79
나영  90   92  81
석영  91   90  89

### #04 특정 행 접근

1. 인덱스 이름으로 접근하기

In [15]:
origin.loc['철수']

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

2. 특정 행의 데이터 타입 확인

In [16]:
type(origin.loc['철수'])

pandas.Series

3. 인덱스 번호를 기반으로 접근

In [17]:
origin.iloc[0]

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

4. 인덱스 번호로 접근할 경우 슬라이싱 가능

In [18]:
origin.iloc[1:4]

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71

### #05 단일 값 확인하기

1. 열 > 행 순서로 접근

In [19]:
origin['국어']['철수']

np.int64(98)

2. 행 > 열 순서로 접근

In [20]:
origin.loc['철수', '국어']

np.int64(98)

3. 인덱스 번호 기반 데이터 접근

In [21]:
# 2번째 행의 3번째 열 데이터
# -> 코드에서는 0부터 카운트
origin.iloc[1, 2]

np.int64(88)

4. 인덱스 번호로 접근할 경우 슬라이싱 가능

In [22]:
# 모든 행에서 4번째 열만 가져옴
# -> 코드에서는 0부터 카운트
origin.iloc[:, 3]

이름
철수     77
영희    120
민철     70
수현     60
호영     50
영호     88
용식     88
나영     92
석영     90
Name: 영어, dtype: int64

### #06 값의 변경

1. 단일값 변경: 행 > 열 순으로 접근하는 경우만 변경 가능

In [23]:
origin.loc['철수', '국어'] = 100
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60  31  71
호영   4  남자   75   50  90  88
영호   4  남자   80   88  91  72
용식   2  남자   82   88  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

2. 열 단위 변경

In [24]:
origin['영어'] = origin['영어'].replace(88, 92)
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60  31  71
호영   4  남자   75   50  90  88
영호   4  남자   80   92  91  72
용식   2  남자   82   92  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

3. 조건에 맞는 행을 검색해 특정 열 변경하기

In [25]:
origin.loc[origin['수학'] < 50, '수학'] = 0
origin

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72
민철   1  남자   92   70  83  79
수현   3  여자   63   60   0  71
호영   4  남자   75   50  90  88
영호   4  남자   80   92  91  72
용식   2  남자   82   92  79  90
나영   1  여자   90   92  81  95
석영   1  남자   91   90  89  80

### #07 데이터 일부만 확인

1. 상위 n건만 확인

In [26]:
origin.head(2)

    학년  성별   국어   영어  수학  과학
이름
철수   1  남자  100   77  88  64
영희   2  여자   88  120  62  72

2. 하위 n건 확인

In [27]:
origin.tail(2)

    학년  성별  국어  영어  수학  과학
이름
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

### #08 기술 통계량 확인

1. 컬럼 단위 확인

In [28]:
print("합계:", origin['국어'].sum())
print("평균:", origin['국어'].mean())
print("최대:", origin['국어'].max())
print("최소:", origin['국어'].min())
print("분산:", origin['국어'].var())
print("표준편차:", origin['국어'].std())
print("중앙값:", origin['국어'].median())
print("1사분위 수:", origin['국어'].quantile(0.25))
print("2사분위 수:", origin['국어'].quantile(0.5))
print("3사분위 수:", origin['국어'].quantile(0.75))

합계: 761
평균: 84.55555555555556
최대: 100
최소: 63
분산: 120.02777777777779
표준편차: 10.955718953029864
중앙값: 88.0
1사분위 수: 80.0
2사분위 수: 88.0
3사분위 수: 91.0

2. DataFrame 단위 확인

In [29]:
origin.sum()

학년                    19
성별    남자여자남자여자남자남자남자여자남자
국어                   761
영어                   743
수학                   663
과학                   711
dtype: object

3. 컬럼 단위로 모든 기술 통계량 일괄 산출

In [30]:
origin['국어'].describe()

count     9.000
mean     84.556
std      10.956
min      63.000
25%      80.000
50%      88.000
75%      91.000
max     100.000
Name: 국어, dtype: float64

4. DataFrame 단위로 일괄 산출

In [31]:
# 연산이 가능한 컬럼만 추출
df2 = origin[['국어', '영어', '수학', '과학']]
desc = df2.describe()
desc

           국어      영어     수학     과학
count   9.000   9.000  9.000  9.000
mean   84.556  82.556 73.667 79.000
std    10.956  20.863 29.026 10.283
min    63.000  50.000  0.000 64.000
25%    80.000  70.000 79.000 72.000
50%    88.000  90.000 83.000 79.000
75%    91.000  92.000 89.000 88.000
max   100.000 120.000 91.000 95.000

5. 전치 구하기

In [32]:
t = desc.T
t

    count   mean    std    min    25%    50%    75%     max
국어  9.000 84.556 10.956 63.000 80.000 88.000 91.000 100.000
영어  9.000 82.556 20.863 50.000 70.000 90.000 92.000 120.000
수학  9.000 73.667 29.026  0.000 79.000 83.000 89.000  91.000
과학  9.000 79.000 10.283 64.000 72.000 79.000 88.000  95.000

### #09 명목형 변수의 기술 통계량 확인

1. 빈도수 구하기 -> 값의 종류별 수

In [33]:
origin['성별'].value_counts()

성별
남자    6
여자    3
Name: count, dtype: int64

2. 명목형 변수의 기술 통계량

In [34]:
origin['학년'].value_counts()

학년
1    4
2    2
4    2
3    1
Name: count, dtype: int64

3. 학년을 포함한 명목형 기술 통계량 집계

In [35]:
origin['학년'] = origin['학년'].astype('category')
origin.describe(include=['object', 'category']).T

C:\Users\itwill\AppData\Local\Temp\ipykernel_1104\2901828846.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  origin.describe(include=['object', 'category']).T

   count unique top freq
학년     9      4   1    4
성별     9      2  남자    6