# [LAB-04] 데이터 다루기

## 2. 데이터 구조 점검(2)

### #01 준비작업

1. 라이브러리 참조

In [2]:
from jussam import load_data
from pandas import Series

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/
🔖 Version: 0.5.21

2. 데이터 가져오기

In [3]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### #02 행, 열 재배치

1. 열 순서 변경

In [4]:
열순서_변경df = origin.reindex(columns=['국어', '수학', '과학', '영어'])
열순서_변경df

    국어  수학  과학   영어
이름
철수  98  88  64   77
영희  88  62  72  120
민철  92  83  79   70
수현  63  31  71   60
호영  75  90  88   50
영호  80  91  72   88
용식  82  79  90   88
나영  90  81  95   92
석영  91  89  80   90

2. 행 순서 변경

In [5]:
행순서_변경df = origin.reindex(index=['석영', '호영', '민철', '수현'])
행순서_변경df

    학년  성별  국어  영어  수학  과학
이름
석영   1  남자  91  90  89  80
호영   4  남자  75  50  90  88
민철   1  남자  92  70  83  79
수현   3  여자  63  60  31  71

### #03 행 추가하기

1. 리스트로 행 추가하기

In [6]:
리스트_행추가df = origin.copy()
리스트_행추가df.loc['정호'] = [2, '남자', 90, 80, 70, 60]
리스트_행추가df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
정호   2  남자  90   80  70  60

2. 딕셔너리로 행 추가하기

In [7]:
딕셔너리_행추가df = origin.copy()
딕셔너리_행추가df.loc['민정'] = {'성별': '여자', '학년': 4, '국어': 81, '영어': 72, '수학': 84, '과학': 90,}
딕셔너리_행추가df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
민정   4  여자  81   72  84  90

3. Series로 행 추가하기

In [8]:
시리즈_행추가df = origin.copy()
s = Series([2, '남자', 90, 80, 70, 60],
            index=['학년', '성별', '국어', '영어', '수학', '과학'])
시리즈_행추가df.loc['형석'] = s
시리즈_행추가df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
형석   2  남자  90   80  70  60

4. 빈 값을 포함하는 행 추가하기

In [9]:
빈값_행추가df = origin.copy()
s = Series([2, '남자', 93, 71],
            index=['학년', '성별', '국어', '수학'])
빈값_행추가df.loc['석호'] = s
빈값_행추가df

    학년  성별  국어      영어  수학     과학
이름
철수   1  남자  98  77.000  88 64.000
영희   2  여자  88 120.000  62 72.000
민철   1  남자  92  70.000  83 79.000
수현   3  여자  63  60.000  31 71.000
호영   4  남자  75  50.000  90 88.000
영호   4  남자  80  88.000  91 72.000
용식   2  남자  82  88.000  79 90.000
나영   1  여자  90  92.000  81 95.000
석영   1  남자  91  90.000  89 80.000
석호   2  남자  93     NaN  71    NaN

5. 기존의 행을 복사해서 행 추가하기

In [10]:
행_복사df = origin.copy()
행_복사df.loc['철민'] = 행_복사df.loc['철수']
행_복사df

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80
철민   1  남자  98   77  88  64

6. 단일 값으로 행 추가하기

In [11]:
단일값_행추가df = origin.copy()
단일값_행추가df.loc['희영'] = 100
단일값_행추가df

     학년   성별   국어   영어   수학   과학
이름
철수    1   남자   98   77   88   64
영희    2   여자   88  120   62   72
민철    1   남자   92   70   83   79
수현    3   여자   63   60   31   71
호영    4   남자   75   50   90   88
영호    4   남자   80   88   91   72
용식    2   남자   82   88   79   90
나영    1   여자   90   92   81   95
석영    1   남자   91   90   89   80
희영  100  100  100  100  100  100

### #04 열 추가하기

1. 리스트로 열 추가하기

In [12]:
리스트_열추가df = origin.copy()
리스트_열추가df['한국사'] = [72, 56, 90, None, 92, 90, 75, 80, 60]
리스트_열추가df

    학년  성별  국어   영어  수학  과학    한국사
이름
철수   1  남자  98   77  88  64 72.000
영희   2  여자  88  120  62  72 56.000
민철   1  남자  92   70  83  79 90.000
수현   3  여자  63   60  31  71    NaN
호영   4  남자  75   50  90  88 92.000
영호   4  남자  80   88  91  72 90.000
용식   2  남자  82   88  79  90 75.000
나영   1  여자  90   92  81  95 80.000
석영   1  남자  91   90  89  80 60.000

2. 딕셔너리로 열 추가하기

In [13]:
딕셔너리_열추가df = origin.copy()
딕셔너리_열추가df['세계사'] = {'철수': 90, '영희': 88, '민철': 72, '수현': 56,
                             '호민': 65, '용식': 77, '나영': 95, '석영': 54}
딕셔너리_열추가df

    학년  성별  국어   영어  수학  과학    세계사
이름
철수   1  남자  98   77  88  64 90.000
영희   2  여자  88  120  62  72 88.000
민철   1  남자  92   70  83  79 72.000
수현   3  여자  63   60  31  71 56.000
호영   4  남자  75   50  90  88    NaN
영호   4  남자  80   88  91  72    NaN
용식   2  남자  82   88  79  90 77.000
나영   1  여자  90   92  81  95 95.000
석영   1  남자  91   90  89  80 54.000

3. Series 객체로 열 추가하기

In [14]:
시리즈_열추가df = origin.copy()
s = Series([72, 56, 90, 88], index=['철수', '민철', '호영', '용식'])
시리즈_열추가df['윤리'] = s
시리즈_열추가df

    학년  성별  국어   영어  수학  과학     윤리
이름
철수   1  남자  98   77  88  64 72.000
영희   2  여자  88  120  62  72    NaN
민철   1  남자  92   70  83  79 56.000
수현   3  여자  63   60  31  71    NaN
호영   4  남자  75   50  90  88 90.000
영호   4  남자  80   88  91  72    NaN
용식   2  남자  82   88  79  90 88.000
나영   1  여자  90   92  81  95    NaN
석영   1  남자  91   90  89  80    NaN

4. 기존의 열을 복사해서 열 추가하기

In [15]:
열_복사df = origin.copy()
열_복사df['체육'] = 열_복사df['과학']
열_복사df

    학년  성별  국어   영어  수학  과학  체육
이름
철수   1  남자  98   77  88  64  64
영희   2  여자  88  120  62  72  72
민철   1  남자  92   70  83  79  79
수현   3  여자  63   60  31  71  71
호영   4  남자  75   50  90  88  88
영호   4  남자  80   88  91  72  72
용식   2  남자  82   88  79  90  90
나영   1  여자  90   92  81  95  95
석영   1  남자  91   90  89  80  80

5. 단일 값으로 열 추가하기

In [16]:
단일값_열추가df = origin.copy()
단일값_열추가df['체육'] = 100
단일값_열추가df

    학년  성별  국어   영어  수학  과학   체육
이름
철수   1  남자  98   77  88  64  100
영희   2  여자  88  120  62  72  100
민철   1  남자  92   70  83  79  100
수현   3  여자  63   60  31  71  100
호영   4  남자  75   50  90  88  100
영호   4  남자  80   88  91  72  100
용식   2  남자  82   88  79  90  100
나영   1  여자  90   92  81  95  100
석영   1  남자  91   90  89  80  100

### #05 행 삭제하기

1. 단일 행 삭제

In [17]:
행_삭제df = origin.copy()
행_삭제df = 행_삭제df.drop(index='철수')
행_삭제df

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

2. 다중 행 삭제

In [18]:
다중삭제df = origin.copy()
다중삭제결과df = 다중삭제df.drop(index=['철수', '민철', '수현'])
다중삭제결과df

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

3. index에 대한 인덱싱으로 행 삭제

In [19]:
인덱싱_행_삭제df = origin.copy()
인덱싱_행_삭제df.index

Index(['철수', '영희', '민철', '수현', '호영', '영호', '용식', '나영', '석영'], dtype='str', name='이름')

In [20]:
인덱싱_행_삭제결과df = 인덱싱_행_삭제df.drop(index=인덱싱_행_삭제df.index[0])
인덱싱_행_삭제결과df

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

4. index에 대한 슬라이싱으로 행 삭제

In [21]:
다중_행_삭제df = origin.copy()
print(다중_행_삭제df.index)

다중_행_삭제결과df = 다중_행_삭제df.drop(index=다중_행_삭제df.index[0:7])
다중_행_삭제결과df

Index(['철수', '영희', '민철', '수현', '호영', '영호', '용식', '나영', '석영'], dtype='str', name='이름')

    학년  성별  국어  영어  수학  과학
이름
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

### #06 열 삭제하기

1. 단일 열 삭제

In [22]:
단일_열_삭제df = origin.copy()
단일_열_삭제결과df = 단일_열_삭제df.drop(columns='학년')
단일_열_삭제결과df

    성별  국어   영어  수학  과학
이름
철수  남자  98   77  88  64
영희  여자  88  120  62  72
민철  남자  92   70  83  79
수현  여자  63   60  31  71
호영  남자  75   50  90  88
영호  남자  80   88  91  72
용식  남자  82   88  79  90
나영  여자  90   92  81  95
석영  남자  91   90  89  80

2. 다중 열 삭제

In [23]:
다중_열_삭제df = origin.copy()
다중_열_삭제결과df = 다중_열_삭제df.drop(columns=['학년', '성별', '과학'])
다중_열_삭제결과df

    국어   영어  수학
이름
철수  98   77  88
영희  88  120  62
민철  92   70  83
수현  63   60  31
호영  75   50  90
영호  80   88  91
용식  82   88  79
나영  90   92  81
석영  91   90  89

3. 컬럼명에 대한 인덱싱으로 열 삭제

In [24]:
인덱싱_열_삭제df = origin.copy()
print(인덱싱_열_삭제df.columns)

인덱싱_열_삭제결과df = 인덱싱_열_삭제df.drop(columns=인덱싱_열_삭제df.columns[0])
인덱싱_열_삭제결과df

Index(['학년', '성별', '국어', '영어', '수학', '과학'], dtype='str')

    성별  국어   영어  수학  과학
이름
철수  남자  98   77  88  64
영희  여자  88  120  62  72
민철  남자  92   70  83  79
수현  여자  63   60  31  71
호영  남자  75   50  90  88
영호  남자  80   88  91  72
용식  남자  82   88  79  90
나영  여자  90   92  81  95
석영  남자  91   90  89  80

4. 컬럼명에 대한 슬라이싱으로 열 삭제

In [25]:
다중_열_삭제df = origin.copy()
print(다중_열_삭제df.columns)

다중_열_삭제결과df = 다중_열_삭제df.drop(columns=다중_열_삭제df.columns[1:-2])
다중_열_삭제결과df

Index(['학년', '성별', '국어', '영어', '수학', '과학'], dtype='str')

    학년  수학  과학
이름
철수   1  88  64
영희   2  62  72
민철   1  83  79
수현   3  31  71
호영   4  90  88
영호   4  91  72
용식   2  79  90
나영   1  81  95
석영   1  89  80

### #07 축을 지정하여 행, 열 삭제

1. 축(axis)을 설정한 단일 행 삭제 방법

In [26]:
df1 = origin.drop('철수')
df1

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

2. 축(axis)을 설정한 다중 행 삭제 방법

In [27]:
df2 = origin.drop(['철수', '영희', '민철', '수현'])
df2

    학년  성별  국어  영어  수학  과학
이름
호영   4  남자  75  50  90  88
영호   4  남자  80  88  91  72
용식   2  남자  82  88  79  90
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

3. 축(axis)을 설정한 열 삭제 방법

In [28]:
df3 = origin.drop(['학년', '성별'], axis=1)
df3

    국어   영어  수학  과학
이름
철수  98   77  88  64
영희  88  120  62  72
민철  92   70  83  79
수현  63   60  31  71
호영  75   50  90  88
영호  80   88  91  72
용식  82   88  79  90
나영  90   92  81  95
석영  91   90  89  80

---

## 연습문제

### 신비한 생물 연구소의 데이터 정리 임무!

당신은 신비한 생물을 연구하는 비밀 연구소의 신입 데이터 분석가입니다.

- 연구원들이 수기로 작성하던 관찰 기록을 처음으로 디지털화했지만, 데이터가 엉망진창입니다.
- 당신의 임무는 이 데이터를 깔끔하게 정리하여 곧 있을 학회 발표 자료로 만드는 것입니다.
- `monsters` 데이터셋을 `DataFrame`으로 불러온 후, 아래의 요구사항에 따라 데이터를 수정하고 최종 결과를 출력하세요.

1. 데이터의 첫인상: 가장 먼저 데이터의 기본적인 정보(`info`)를 파악하세요.
2. 쓸모없는 정보 삭제: `last_seen` 열은 이번 발표에 필요 없는 정보입니다. 해당 열을 데이터에서 삭제하세요.
3. 신규 개체 추가: 최근 `M021` ID를 가진 신규 개체 `Kelpie`가 발견되었습니다.   
    아래 정보를 가진 행을 `Series` 객체로 생성한 후 `DataFrame`에 새로운 행으로 추가하세요. 이 개체의 `weight`는 측정되지 않았습니다.

| 항목 | 값 |
|---|---|
| 몬스터 고유 ID | M021 |
| 생물 종 | Kelpie |
| 서식지 | Lake |
| 키 | 2.2m |
| 위험 등급 | Medium |
| 몸무게 | 측정되지 않음 |

4. 데이터 오류 수정: `M004` 개체는 사실 `M003` 개체를 잘못 기록한 것입니다.   
    `M004` 행의 모든 데이터를 `M003` 행의 데이터와 동일하게 수정한 후, `M004` 행의 ID를 `M003_copy`로 변경하세요.
5. 최종 보고서용 정렬: 발표 자료는 `monster_id`, `caution_level`, `species`, `habitat`, `height`, `weight` 순서로 열이 정렬되어야 합니다.   
    최종 `DataFrame`의 열 순서를 이 순서에 맞게 재배치하세요.

In [29]:
# 1. 라이브러리 참조
from jussam import load_data
from pandas import Series

# 2. 데이터 불러오기
origin = load_data("monsters")

# 3. 기본 정보 파악
origin.info()

📚 신비한 생물 연구소의 몬스터 데이터

    field          description
--  -------------  ----------------------
 0  monster_id     몬스터 고유 ID(인덱스)
 1  last_seen      마지막으로 관찰된 날짜
 2  species        생물 종
 3  habitat        서식지
 4  height         키 (m)
 5  weight         몸무게 (kg)
 6  caution_level  위험 등급

<class 'pandas.DataFrame'>
Index: 20 entries, M001 to M020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   last_seen      20 non-null     datetime64[us]
 1   species        20 non-null     str
 2   habitat        20 non-null     str
 3   height         20 non-null     float64
 4   weight         20 non-null     float64
 5   caution_level  20 non-null     str
dtypes: datetime64[us](1), float64(2), str(3)
memory usage: 1.5 KB

In [31]:
# 4. 특정 행 삭제
delete_origin = origin.copy()
deleted_origin = delete_origin.drop(columns='last_seen')

# 5. 새로운 행을 시리즈로 추가
# s = Series({'height': 2.2, 'species': 'Kelpie', 'caution_level': 'Medium'})
s = Series(['Kelpie', 'Lake', 2.2, 'Medium'],
            index=['species', 'habitat', 'height', 'caution_level'])
deleted_origin.loc['M021'] = s

# 6. 데이터 오류 수정
deleted_origin.loc['M004'] = deleted_origin.loc['M003']
renamed_origin = deleted_origin.rename(index={'M004': 'M003_copy'}).reset_index()

# 7. 컬럼 정렬
final_origin = renamed_origin.reindex(columns=['monster_id', 'caution_level', 'species', 'habitat', 'height', 'weight'])
final_origin

   monster_id caution_level   species   habitat  height    weight
0        M001          High   Griffin  Mountain   2.500   150.500
1        M002           Low   Unicorn    Forest   2.100   120.000
2        M003     Very High    Dragon   Volcano  15.200  5500.000
3   M003_copy     Very High    Dragon   Volcano  15.200  5500.000
4        M005          High    Kraken     Ocean  30.500 15000.000
5        M006        Medium   Phoenix    Desert   1.800    25.500
6        M007           Low   Mermaid     Ocean   1.900    65.500
7        M008        Medium    Goblin      Cave   1.100    40.200
8        M009           Low     Fairy    Forest   0.300     0.500
9        M010          High     Hydra     Swamp   5.500   800.000
10       M011          High   Cyclops    Island   8.200  2500.000
11       M012           Low     Gnome    Garden   0.400     5.100
12       M013        Medium      Yeti  Mountain   3.500   300.000
13       M014        Medium    Sphinx    Desert   2.800   180.000
14       M015          High   Banshee     Ruins   1.700    45.000
15       M016          High  Werewolf    Forest   2.300   110.000
16       M017          High   Vampire    Castle   1.800    75.000
17       M018     Very High   Chimera  Mountain   3.100   450.000
18       M019     Very High  Basilisk     Sewer   4.000   200.000
19       M020        Medium  Gargoyle   Rooftop   2.000   500.000
20       M021        Medium    Kelpie      Lake   2.200       NaN