# [LAB-04] 데이터 다루기

## 5. 데이터 병합

### #01 준비작업

1. 패키지 참조

In [1]:
from jussam import load_data
from pandas import DataFrame
from pandas import merge, concat

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/
🔖 Version: 0.5.21

2. 첫번째 샘플 데이터 가져오기

In [2]:
고객 = load_data("customer_no_name")
고객

📚 데이터프레임 병합 실습을 위한 고객번호와 고객 이름에 대한 가상 데이터(인덱스와 메타데이터 없음)

   고객번호   이름
0  1001   둘리
1  1002  도우너
2  1003   또치
3  1004   길동
4  1005   희동
5  1006  마이콜
6  1007   영희

3. 두 번째 샘플 가져오기

In [3]:
매출 = load_data("customer_no_pay")
매출

📚 데이터프레임 병합 실습을 위한 고객번호와 매출액에 대한 가상 데이터(인덱스와 메타데이터 없음)

   고객번호      금액
0  1001   10000
1  1001   20000
2  1005   15000
3  1006    5000
4  1008  100000
5  1001   30000

### #02 열 기준 병합

1. 일치하는 데이터끼리 병합

In [4]:
merge(고객, 매출)

   고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

2. 왼쪽 데이터 프레임을 기준으로 병합

In [5]:
merge(고객, 매출, how="left")

   고객번호   이름        금액
0  1001   둘리 10000.000
1  1001   둘리 20000.000
2  1001   둘리 30000.000
3  1002  도우너       NaN
4  1003   또치       NaN
5  1004   길동       NaN
6  1005   희동 15000.000
7  1006  마이콜  5000.000
8  1007   영희       NaN

3. 오른쪽 데이터 프레임을 기준으로 병합

In [6]:
merge(고객, 매출, how="right")

   고객번호   이름      금액
0  1001   둘리   10000
1  1001   둘리   20000
2  1005   희동   15000
3  1006  마이콜    5000
4  1008  NaN  100000
5  1001   둘리   30000

4. 모든 데이터의 교차 병합 (합집합)

In [7]:
merge(고객, 매출, how="outer")

   고객번호   이름         금액
0  1001   둘리  10000.000
1  1001   둘리  20000.000
2  1001   둘리  30000.000
3  1002  도우너        NaN
4  1003   또치        NaN
5  1004   길동        NaN
6  1005   희동  15000.000
7  1006  마이콜   5000.000
8  1007   영희        NaN
9  1008  NaN 100000.000

### #03 병합 기준 열 지정하기

1. 샘플 데이터 가져오기

In [8]:
cd1 = load_data("customer_data1")
cd1

📚 데이터 병합용 실습 데이터 (1) (인덱스/메타데이터 없음)

  고객명         날짜     데이터
0  민수 2018-01-01   20000
1  수영 2018-01-01  100000

In [9]:
cd2 = load_data("customer_data2")
cd2

📚 데이터 병합용 실습 데이터 (2) (인덱스/메타데이터 없음)

  고객명  데이터
0  민수  21세
1  수영  20세

2. 기본 병합

In [10]:
merge(cd1, cd2)         # 두 데이터프레임에서 '데이터'라는 이름의 변수가 서로 타입이 다르므로 병합되지 않고 에러 발생

ValueError: You are trying to merge on int64 and str columns for key '데이터'. If you wish to proceed you should use pd.concat

3. 병합 기준 설정

In [ ]:
tmp = merge(cd1, cd2, on='고객명')
tmp

  고객명         날짜   데이터_x 데이터_y
0  민수 2018-01-01   20000   21세
1  수영 2018-01-01  100000   20세

4. 두 데이터 프레임의 모든 컬럼 이름이 다른 경우

In [ ]:
df_left = DataFrame({'이름': ['영희', '철수'], '국어': [87, 91]})
df_left

   이름  국어
0  영희  87
1  철수  91

In [ ]:
df_right = DataFrame({'성명': ['영희', '철수'], '영어': [90, 82]})
df_right

   성명  영어
0  영희  90
1  철수  82

In [ ]:
r3 = merge(df_left, df_right, left_on=['이름'], right_on=['성명'])
r3

   이름  국어  성명  영어
0  영희  87  영희  90
1  철수  91  철수  82

### #04 인덱스를 활용한 병합

1. 학생의 이름을 인덱스로 갖는 두 데이터 프레임 생성

In [ ]:
df_left = DataFrame({'수학': [90, 82]}, index=['민철', '봉구'])
df_left

    수학
민철  90
봉구  82

In [ ]:
df_right = DataFrame({'국어': [90, 82]}, index=['민철', '철수'])
df_right

    국어
민철  90
철수  82

2. 병합 조건에서 index를 사용하도록 지정하여 Inner Join하기

In [ ]:
merge(df_left, df_right, left_index=True, right_index=True)

    수학  국어
민철  90  90

3. 병합 조건에서 index를 사용하도록 지정하여 Left Outer Join하기

In [ ]:
merge(df_left, df_right, left_index=True, right_index=True, how="left")

    수학     국어
민철  90 90.000
봉구  82    NaN

4. 병합 조건에서 index를 사용하도록 지정하여 Right Outer Join하기

In [ ]:
merge(df_left, df_right, left_index=True, right_index=True, how="right")

       수학  국어
민철 90.000  90
철수    NaN  82

5. 병합 조건에서 index를 사용하도록 지정하여 Full Outer Join하기

In [ ]:
merge(df_left, df_right, left_index=True, right_index=True, how="outer")

       수학     국어
민철 90.000 90.000
봉구 82.000    NaN
철수    NaN 82.000

### #05 인덱스와 컬럼을 각각 기준으로 하기

1. 샘플 데이터 프레임 생성

In [ ]:
df_left = DataFrame({'수학': [90, 82]}, index=['민철', '봉구'])
df_left

    수학
민철  90
봉구  82

In [ ]:
df_right = DataFrame({'성명': ['민철', '철수'], '영어': [90, 82]})
df_right

   성명  영어
0  민철  90
1  철수  82

2. 왼쪽은 인덱스, 오른쪽은 컬럼을 기준으로 Inner Join

In [ ]:
merge(df_left, df_right, left_index=True, right_on=['성명'])

   수학  성명  영어
0  90  민철  90

3. 왼쪽은 인덱스, 오른쪽은 컬럼을 기준으로 Left Outer Join

In [ ]:
merge(df_left, df_right, left_index=True, right_on=['성명'], how='left')

       수학  성명     영어
0.000  90  민철 90.000
NaN    82  봉구    NaN

4. 왼쪽은 인덱스, 오른쪽은 컬럼을 기준으로 Right Outer Join

In [ ]:
merge(df_left, df_right, left_index=True, right_on=['성명'], how='right')

      수학  성명  영어
0 90.000  민철  90
1    NaN  철수  82

5. 왼쪽은 인덱스, 오른쪽은 컬럼을 기준으로 Full Outer Join

In [ ]:
tmp = merge(df_left, df_right, left_index=True, right_on=['성명'], how='outer')
tmp

          수학  성명     영어
0.000 90.000  민철 90.000
NaN   82.000  봉구    NaN
1.000    NaN  철수 82.000

6. 병합 후에는 인덱스를 정리해야 한다.

In [ ]:
tmp2 = tmp.set_index('성명')
tmp2

       수학     영어
성명
민철 90.000 90.000
봉구 82.000    NaN
철수    NaN 82.000

### #06 행 기준 병합

1. 샘플 데이터 생성

In [ ]:
df1 = DataFrame({'이름': ['영희', '철수'], '국어': [87, 91]})
df1

   이름  국어
0  영희  87
1  철수  91

In [ ]:
df2 = DataFrame({'이름': ['민철', '수현'], '국어': [78, 92]})
df2

   이름  국어
0  민철  78
1  수현  92

2. concat() 함수 기본 사용 방법

In [ ]:
concat([df1, df2])

   이름  국어
0  영희  87
1  철수  91
0  민철  78
1  수현  92

3. 병합 결과에서 index를 재구성하기(1)

In [ ]:
인덱스_재구성df = concat([df1, df2])
인덱스_재구성df.reset_index(inplace=True, drop=True)
인덱스_재구성df

   이름  국어
0  영희  87
1  철수  91
2  민철  78
3  수현  92

4. 병합 결과에서 index를 재구성하기(2)

In [ ]:
concat([df1, df2], ignore_index=True)

   이름  국어
0  영희  87
1  철수  91
2  민철  78
3  수현  92

### #07 서로 다른 변수를 갖는 데이터 프레임의 병합

1, 샘플 데이터 구성

In [ ]:
df3 = DataFrame({'이름': ['영희', '철수'], '국어': [87, 91]})
df3

   이름  국어
0  영희  87
1  철수  91

In [ ]:
df4 = DataFrame({'이름': ['민철', '수현'], '수학': [78, 92]})
df4

   이름  수학
0  민철  78
1  수현  92

2. 데이터 병합

In [ ]:
concat([df3, df4], ignore_index=True)

   이름     국어     수학
0  영희 87.000    NaN
1  철수 91.000    NaN
2  민철    NaN 78.000
3  수현    NaN 92.000

### #08 인덱스를 갖는 데이터 프레임의 병합

1. 샘플 데이터 구성

In [ ]:
df5 = DataFrame({'국어': [87, 91, 85]}, index=['영희', '철수', '민수'])
df5

    국어
영희  87
철수  91
민수  85

In [ ]:
df6 = DataFrame({'국어': [78, 92, 82]}, index=['민철', '수현', '민수'])
df6

    국어
민철  78
수현  92
민수  82

2. 데이터 병합

In [ ]:
concat([df5, df6])

    국어
영희  87
철수  91
민수  85
민철  78
수현  92
민수  82

3. 인덱스를 제외하고 병합하기

In [ ]:
concat([df5, df6], ignore_index=True)

   국어
0  87
1  91
2  85
3  78
4  92
5  82

---

## 연습문제

### 1. 고객 데이터와 구매 데이터를 통합하여, 연령대별 평균 구매액 분석하기

- 팀장님께서 고객 정보와 최근 구매 내역 데이터를 전달해 주셨습니다. 하지만 데이터가 완벽하지는 않네요. 여러분의 데이터 분석 스킬을 발휘하여 아래 요구사항에 따라 데이터를 정제하고 분석 리포트를 만들어주세요.

- 고객 정보 > 직접 생성해야 합니다.

| 변수명 | 데이터 |
|---|---|
| `customer_id` | 101, 102, 103, 104, 105, 106 |
| `name` | 'Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank' |
| `age` | 25, 32, 45, 38, 29, 41 |
- 구매내역: `order_history` 데이터셋으로 가져올 수 있습니다.

- 요구사항

1. 구매 데이터의 `price` 컬럼에 있는 결측치는 전체 상품의 **평균 가격**으로 채워주세요.

2. 정제된 두 데이터프레임을 `customer_id` 기준으로 병합하세요.

3. 최종 병합된 데이터 프레임에 대한 **기술 통계량**을 도출하세요.

In [ ]:
# 1. 라이브러리 참조
from jussam import load_data
from pandas import DataFrame
from pandas import merge, concat

# 2. 구매 내역 데이터 불러오기
order_df = load_data('order_history')

# 3. 고객 정보 생성
data = {
    "customer_id": [101, 102, 103, 104, 105, 106],
    "name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    "age": [25, 32, 45, 38, 29, 41]
}

customer_df = DataFrame(data)

display(order_df)
display(customer_df)

📚 신입 데이터 분석가를 위한 실전 미션!

    field        description
--  -----------  ----------------
 0  purchase_id  일련번호(인덱스)
 1  customer_id  고객번호
 2  item         상품명
 3  price        금액

             customer_id             item    price
purchase_id
1                    101           Laptop 1200.000
2                    102            Mouse   25.000
3                    103         Keyboard      NaN
4                    101          Monitor  300.000
5                    104           Webcam 5000.000
6                    102          USB Hub   30.000
7                    105           Laptop 1100.000
8                    103            Mouse      NaN
9                    101     External HDD   80.000
10                   106  Docking Station  150.000

   customer_id     name  age
0          101    Alice   25
1          102      Bob   32
2          103  Charlie   45
3          104    David   38
4          105      Eve   29
5          106    Frank   41

In [ ]:
# 4. 구매 데이터 결측치 대체
#imr = SimpleImputer(missing_values=np.nan, strategy='mean')
#reshape = order_df['price'].values.reshape(-1, 1)
#reshape_imr = imr.fit_transform(reshape)
#order_df['price'] = reshape_imr

결측치처리 = order_df.copy()        # 원본 복사
average_price = 결측치처리['price'].mean()      # 전체 상품의 평균 가격
결측치처리_결과 = 결측치처리['price'].fillna(average_price)     # 평균 가격으로 결측치 대체
결측치처리['price'] = 결측치처리_결과       # Series 객체를 원본 데이터프레임의 price 컬럼에 대입

결측치처리

             customer_id             item    price
purchase_id
1                    101           Laptop 1200.000
2                    102            Mouse   25.000
3                    103         Keyboard  985.625
4                    101          Monitor  300.000
5                    104           Webcam 5000.000
6                    102          USB Hub   30.000
7                    105           Laptop 1100.000
8                    103            Mouse  985.625
9                    101     External HDD   80.000
10                   106  Docking Station  150.000

In [ ]:
# 5. 두 데이터 프레임을 customer_id 기준으로 병합
final_df = merge(결측치처리, customer_df, on='customer_id')
final_df

   customer_id             item    price     name  age
0          101           Laptop 1200.000    Alice   25
1          102            Mouse   25.000      Bob   32
2          103         Keyboard  985.625  Charlie   45
3          101          Monitor  300.000    Alice   25
4          104           Webcam 5000.000    David   38
5          102          USB Hub   30.000      Bob   32
6          105           Laptop 1100.000      Eve   29
7          103            Mouse  985.625  Charlie   45
8          101     External HDD   80.000    Alice   25
9          106  Docking Station  150.000    Frank   41

In [ ]:
# 6. 최종 데이터 프레임에 대한 기술 통계량 도출
final_df.describe().T.drop('customer_id')

       count    mean      std    min    25%     50%      75%      max
price 10.000 985.625 1490.666 25.000 97.500 642.812 1071.406 5000.000
age   10.000  33.700    8.042 25.000 26.000  32.000   40.250   45.000

### 2. 흩어진 판매 데이터 통합하기

당신은 IT 쇼핑몰의 신입 데이터 분석가입니다.

- 회사에는 강남점과 종로점, 두 개의 지점이 있습니다.
- 각 지점의 판매 데이터가 별도의 데이터(`shop_강남`, `shop_종로`)로 관리되고 있었습니다.

연말 보고를 위해 두 지점의 데이터를 하나로 합쳐 **전체 판매 실적을 분석**해야 합니다.

- 하지만 데이터를 살펴보니 몇 가지 정리할 부분이 보입니다.
- 당신의 임무는 데이터를 정제하고 통합하여 의미있는 리포트를 만드는 것입니다.

#### 요구사항

1. 강남점 데이터에는 `Mouse` 상품의 가격(`Price`)이 누락되어 있습니다.  
   이 값을 `8000`으로 채워주세요.

2. 종로점 데이터에는 `Keyboard` 상품의 주문 수량(`Quantity`)이 `999`로 잘못 입력되어 있습니다.  
   실제 수량은 `9`이므로, 이 값을 수정해주세요.

3. 두 개의 `DataFrame`을 하나의 `DataFrame`으로 합치세요.  
   합치는 과정에서 기존의 인덱스는 의미가 없으므로, 새로운 인덱스를 부여하세요.

4. 화면에 최종 `DataFrame`의 전체 내용을 출력하세요.

In [ ]:
# 1. 라이브러리 참조
import numpy as np
from jussam import load_data
from pandas import DataFrame
from sklearn.impute import SimpleImputer

# 2. 데이터 불러오기
shop_gn = load_data('shop_강남')
shop_jl = load_data('shop_종로')

display(shop_gn)
display(shop_jl)

📚 흩어진 판매 데이터 통합하기(인덱스/메타데이터 없음)
📚 흩어진 판매 데이터 통합하기(인덱스/메타데이터 없음)

  OrderID   Product  Quantity     Price
0    A001  Keyboard        10 15000.000
1    A002     Mouse        20       NaN
2    A003   Monitor         5 75000.000
3    A004  Keyboard        12 15000.000

  OrderID   Product  Quantity  Price
0    B001     Mouse        15   8000
1    B002  Keyboard       999  14500
2    B003    Webcam        10  30000
3    B004     Mouse        18   8000

In [ ]:
# 3. 강남점 결측치를 8000으로 대체
re_shop_gn = shop_gn.copy()
re_shop_gn.loc[1, 'Price'] = 8000
re_shop_gn

  OrderID   Product  Quantity     Price
0    A001  Keyboard        10 15000.000
1    A002     Mouse        20  8000.000
2    A003   Monitor         5 75000.000
3    A004  Keyboard        12 15000.000

In [ ]:
# 4. 종로점 데이터 수정하기
shop_jl_cp = shop_jl.copy()
shop_jl_cp.loc[shop_jl.Product == "Keyboard", "Quantity"] = 9
shop_jl_cp

  OrderID   Product  Quantity  Price
0    B001     Mouse        15   8000
1    B002  Keyboard         9  14500
2    B003    Webcam        10  30000
3    B004     Mouse        18   8000

In [ ]:
# 5. 두 개의 데이터 프레임을 병합하고 새로운 인덱스 부여
final_df = concat([re_shop_gn, shop_jl_cp], ignore_index=True)

In [ ]:
# 6. 최종 데이터 프레임 출력
final_df

  OrderID   Product  Quantity     Price
0    A001  Keyboard        10 15000.000
1    A002     Mouse        20  8000.000
2    A003   Monitor         5 75000.000
3    A004  Keyboard        12 15000.000
4    B001     Mouse        15  8000.000
5    B002  Keyboard         9 14500.000
6    B003    Webcam        10 30000.000
7    B004     Mouse        18  8000.000