# [LAB-04] 데이터 다루기

## 6. 데이터 정렬, 필터링

### #01 준비작업

1. 라이브러리 참조

In [9]:
from jussam import load_data

📦 연세대학교 주영아 교수가 제작한 라이브러리를 사용중입니다.
📧 Email(1): j.purplerose@yonsei.ac.kr
📧 Email(2): j.purplerose@gmail.com
📝 Website: https://juyounga.kr/
🔖 Version: 0.5.21

2. 데이터 불러오기

In [10]:
origin = load_data('grade')
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### #02 데이터 정렬

1. 변수에 의한 정렬

In [11]:
단일정렬df = origin.sort_values('학년', ascending=False)
단일정렬df

    학년  성별  국어   영어  수학  과학
이름
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
수현   3  여자  63   60  31  71
용식   2  남자  82   88  79  90
영희   2  여자  88  120  62  72
철수   1  남자  98   77  88  64
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

2. 여러 변수 정렬

In [12]:
복수정렬df = origin.sort_values(['학년', '국어'], ascending=[False, False])
복수정렬df

    학년  성별  국어   영어  수학  과학
이름
영호   4  남자  80   88  91  72
호영   4  남자  75   50  90  88
수현   3  여자  63   60  31  71
영희   2  여자  88  120  62  72
용식   2  남자  82   88  79  90
철수   1  남자  98   77  88  64
민철   1  남자  92   70  83  79
석영   1  남자  91   90  89  80
나영   1  여자  90   92  81  95

3. 인덱스를 기준으로 하는 정렬

In [13]:
인덱스정렬df = origin.sort_index(ascending=False)
인덱스정렬df

    학년  성별  국어   영어  수학  과학
이름
호영   4  남자  75   50  90  88
철수   1  남자  98   77  88  64
용식   2  남자  82   88  79  90
영희   2  여자  88  120  62  72
영호   4  남자  80   88  91  72
수현   3  여자  63   60  31  71
석영   1  남자  91   90  89  80
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95

### #03 데이터 필터링

1. 숫자형 변수의 조건 검색

In [14]:
# r1 = origin[origin['국어'] > 80]
r1 = origin.query('국어 > 80')
r1

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

2. 문자열 변수의 조건 검색

In [15]:
# r2 = origin[origin["성별"] == '남자]
r2 = origin.query("성별 == '남자'")
r2

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
민철   1  남자  92  70  83  79
호영   4  남자  75  50  90  88
영호   4  남자  80  88  91  72
용식   2  남자  82  88  79  90
석영   1  남자  91  90  89  80

3. AND 연산을 사용하는 조건 검색

In [16]:
# r3 = origin[(origin['국어'] > 80) & (origin['수학']) > 80]
r3 = origin.query('국어 > 80 and 수학 > 80')
r3

    학년  성별  국어  영어  수학  과학
이름
철수   1  남자  98  77  88  64
민철   1  남자  92  70  83  79
나영   1  여자  90  92  81  95
석영   1  남자  91  90  89  80

4. OR 연산을 사용하는 조건 검색

In [17]:
# r4 = origin[(origin['국어'] <= 80) | (origin['수학']) <= 80]
r4 = origin.query('국어 <= 80 or 수학 <= 80')
r4

    학년  성별  국어   영어  수학  과학
이름
영희   2  여자  88  120  62  72
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90

5. 비교식에 변수를 사용하는 조건 검색

In [18]:
point = int(input('점수를 입력하세요: '))
print("국어 점수가 %d점보다 높은 학생" % point)

r5 = origin.query('국어 > @point')          # @변수이름 형태로 조건식에 포함
r5

국어 점수가 82점보다 높은 학생

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

6. 열 단위 필터링

In [19]:
fl = origin.filter(['국어', '영어'])
fl

    국어   영어
이름
철수  98   77
영희  88  120
민철  92   70
수현  63   60
호영  75   50
영호  80   88
용식  82   88
나영  90   92
석영  91   90

---

## 연습문제

### 마케팅팀 신입사원의 첫 번째 미션

**VIP 고객을 찾아라!**
- 당신은 방금 우리 회사 마케팅팀에 입사한 신입사원입니다.
- 팀장님께서 당신에게 첫 번째 미션을 주셨습니다. 연말을 맞이하여 VIP 고객들에게 감사의 마음을 담은 특별 선물을 보내려고 합니다.
- 당신의 임무는 제공된 고객 데이터 vip_customer를 분석하여 VIP 고객 후보 명단을 만드는 것입니다.   

**아래의 조건들을 모두 만족하는 진정한 VIP 고객을 찾아내어, 그들의 명단을 팀장님께 보고해야 합니다.**
1. 우수 고객: 총 구매액(TotalSpending)이 100,000원 이상인 고객
2. 활동지역 고객: 서울(City)에 거주하는 고객   

**보고할 내용**
- 위 세 가지 조건을 모두 만족하는 고객들을 총 구매액(TotalSpending)이 높은 순서대로 정렬하여 상위 5명의 고객 정보를 추출하세요.
- 추출된 5명의 고객 데이터에서 Name, City, TotalSpending만 선택하여 최종 명단을 만드세요.

In [2]:
from jussam import load_data

vip = load_data('vip_customer')

vip_filtered = vip.query('TotalSpending >= 100000 and City == "서울"')
vip_sorted = vip_filtered.sort_values('TotalSpending', ascending=False).head()
vip_final = vip_sorted.filter(['Name', 'City', 'TotalSpending'])

vip_final

📚 VIP 고객 목록 데이터

    field             description
--  ----------------  ----------------
 0  CustomerID        고객번호
 1  Name              고객명
 2  Age               나이
 3  City              거주지역
 4  JoinDate          가입일
 5  TotalSpending     총 지출액
 6  LastPurchaseDate  마지막 구매 날짜

           Name City  TotalSpending
CustomerID
1009        한지민   서울         450000
1005        정다솜   서울         320000
1003        박민준   서울         250000
1011        임도윤   서울         210000
1013        황재민   서울         190000