# [LAB-04] 데이터 다루기

## 9. 파생변수

### #01 준비작업

1. 라이브러리 참조

In [ ]:
from jussam import load_data
from pandas import cut
import numpy as np

2. 데이터 가져오기

In [ ]:
origin = load_data("grade")
origin

📚 어느 학급의 과목별 점수를 조사한 가상의 데이터

    학년  성별  국어   영어  수학  과학
이름
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

### #02 파생변수 추가하기

1. 컬럼 연산을 통한 새로운 컬럼 추가

In [ ]:
df1 = origin.copy()
df1['직접합계'] = df1['국어'] + df1['영어'] + df1['수학'] + df1['과학']
df1

    학년  성별  국어   영어  수학  과학  직접합계
이름
철수   1  남자  98   77  88  64   327
영희   2  여자  88  120  62  72   342
민철   1  남자  92   70  83  79   324
수현   3  여자  63   60  31  71   225
호영   4  남자  75   50  90  88   303
영호   4  남자  80   88  91  72   331
용식   2  남자  82   88  79  90   339
나영   1  여자  90   92  81  95   358
석영   1  남자  91   90  89  80   350

2. 기술통계 관련 함수를 사용한 파생변수

- 컬럼 이름에 대한 슬라이싱 접근
axis=1 : x축 / axis=0 : y축

In [19]:
df2 = origin.copy()
df2['합계'] = df2[df2.columns[2:6]].sum(axis=1)
df2

    학년  성별  국어   영어  수학  과학   합계
이름
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

- 인덱스 기반 위치로 슬라이싱하여 합계 변수 추가

In [23]:
df3 = origin.copy()
df3['합계'] = df3.iloc[:, 2:].sum(axis=1)
df3

    학년  성별  국어   영어  수학  과학   합계
이름
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

- 나머지 기술통계값 추가

In [28]:
df3['평균'] = df3.iloc[:, 2:6].mean(axis=1)
df3['최대값'] = df3.iloc[:, 2:6].max(axis=1)
df3['최소값'] = df3.iloc[:, 2:6].min(axis=1)
df3['표준편차'] = df3.iloc[:, 2:6].std(axis=1)
df3['분산'] = df3.iloc[:, 2:6].var(axis=1)
df3

    학년  성별  국어   영어  수학  과학   합계     평균  최대값  최소값   표준편차      분산
이름
철수   1  남자  98   77  88  64  327 81.750   98   64 14.614 213.583
영희   2  여자  88  120  62  72  342 85.500  120   62 25.371 643.667
민철   1  남자  92   70  83  79  324 81.000   92   70  9.129  83.333
수현   3  여자  63   60  31  71  225 56.250   71   31 17.462 304.917
호영   4  남자  75   50  90  88  303 75.750   90   50 18.410 338.917
영호   4  남자  80   88  91  72  331 82.750   91   72  8.539  72.917
용식   2  남자  82   88  79  90  339 84.750   90   79  5.123  26.250
나영   1  여자  90   92  81  95  358 89.500   95   81  6.028  36.333
석영   1  남자  91   90  89  80  350 87.500   91   80  5.066  25.667

### #03 조건별 파생 변수

1. if~else

- 실습을 위해 합계와 평균에 대한 파생 변수 추가

In [32]:
df4 = origin.copy()
df4['합계'] = df4.iloc[:, 2:6].sum(axis=1)
df4['평균'] = df4.iloc[:, 2:6].mean(axis=1)

df4

    학년  성별  국어   영어  수학  과학   합계     평균
이름
철수   1  남자  98   77  88  64  327 81.750
영희   2  여자  88  120  62  72  342 85.500
민철   1  남자  92   70  83  79  324 81.000
수현   3  여자  63   60  31  71  225 56.250
호영   4  남자  75   50  90  88  303 75.750
영호   4  남자  80   88  91  72  331 82.750
용식   2  남자  82   88  79  90  339 84.750
나영   1  여자  90   92  81  95  358 89.500
석영   1  남자  91   90  89  80  350 87.500

- NumPy의 where 함수를 사용한 조건부 파생 변수

In [34]:
df4['결과1'] = np.where(df4['평균'] >= 80, '합격', '불합격')
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1
이름
철수   1  남자  98   77  88  64  327 81.750   합격
영희   2  여자  88  120  62  72  342 85.500   합격
민철   1  남자  92   70  83  79  324 81.000   합격
수현   3  여자  63   60  31  71  225 56.250  불합격
호영   4  남자  75   50  90  88  303 75.750  불합격
영호   4  남자  80   88  91  72  331 82.750   합격
용식   2  남자  82   88  79  90  339 84.750   합격
나영   1  여자  90   92  81  95  358 89.500   합격
석영   1  남자  91   90  89  80  350 87.500   합격

- 표현식을 사용한 평균값에 따른 조건부 파생변수

In [36]:
df4['결과2'] = "불합격"
df4.loc[df4['평균'] >= 80, '결과2'] = '합격'
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격
영희   2  여자  88  120  62  72  342 85.500   합격   합격
민철   1  남자  92   70  83  79  324 81.000   합격   합격
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격
영호   4  남자  80   88  91  72  331 82.750   합격   합격
용식   2  남자  82   88  79  90  339 84.750   합격   합격
나영   1  여자  90   92  81  95  358 89.500   합격   합격
석영   1  남자  91   90  89  80  350 87.500   합격   합격

2. 경우의 수에 따른 조건값(elif) - NumPy의 select 함수 사용

In [38]:
# 학점을 부여하기 위한 점수의 구간을 설정하는 조건들을 리스트로 설정
conditions = [(df4['평균'] >= 90),      # if
              (df4['평균'] >= 80),      # elif
              (df4['평균'] >= 70)]      # elif

# 조건에 따라 부여될 학점
value = ['A', 'B', 'C']

df4['학점1'] = np.select(conditions, value, default='F')
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B

3. 사용자 정의 함수 사용

- 사용자 정의 함수

In [44]:
# 함수 정의하기
def getScore(x):
    if x >= 90:
        score = 'A'
    elif x >= 80:
        score = 'B'
    elif x >= 70:
        score = 'C'
    else:
        score = 'F'

    return score

# 함수 리턴값으로 파생변수 추가하기

df4['학점2'] = df4['평균'].apply(getScore)
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B

- 함수 정의 없이 람다식으로 익명함수 적용하기

In [55]:
df4['학점'] = df4['평균'].apply(
    lambda x: {10: "A", 9: "A", 8: "B", 7: "C"}.get(x // 10, "F"))
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 성별코드 학점4 학점
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B    M   B  B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B    F   B  B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B    M   B  B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F    F   F  F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C    M   C  C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B    M   B  B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B    M   B  B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B    F   B  B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B    M   B  B

4. map() 메서드 사용

In [47]:
df4['성별코드'] = df4['성별'].map({"남자": "M", "여자": "F"})
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 성별코드
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B    M
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B    F
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B    M
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F    F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C    M
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B    M
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B    M
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B    F
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B    M

5. Pandas의 cut 함수 사용

In [51]:
df4["학점4"] = cut(
    df4["평균"],     # 대상 컬럼
    bins=[0, 70, 80, 90, 100],      # 구간 설정
    labels=["F", "C", "B", "A"],        # 구간별 값 설정
)
df4

    학년  성별  국어   영어  수학  과학   합계     평균  결과1  결과2 학점1 학점2 성별코드 학점4
이름
철수   1  남자  98   77  88  64  327 81.750   합격   합격   B   B    M   B
영희   2  여자  88  120  62  72  342 85.500   합격   합격   B   B    F   B
민철   1  남자  92   70  83  79  324 81.000   합격   합격   B   B    M   B
수현   3  여자  63   60  31  71  225 56.250  불합격  불합격   F   F    F   F
호영   4  남자  75   50  90  88  303 75.750  불합격  불합격   C   C    M   C
영호   4  남자  80   88  91  72  331 82.750   합격   합격   B   B    M   B
용식   2  남자  82   88  79  90  339 84.750   합격   합격   B   B    M   B
나영   1  여자  90   92  81  95  358 89.500   합격   합격   B   B    F   B
석영   1  남자  91   90  89  80  350 87.500   합격   합격   B   B    M   B

---

## 연습문제

### 우수 고객을 찾아라! - 영업 데이터 분석 챌린지

**한 온라인 쇼핑몰의 마케팅팀은 연말을 맞아 우수 고객에게 감사의 선물을 보내기로 했습니다.**
- 팀은 최근의 주문 데이터인 online_shop_sales를 가지고 있지만, 어떤 고객이 가장 많은 금액을 지출했는지 한눈에 파악하기 어렵습니다.
- 여러분은 데이터 분석가가 되어 마케팅팀의 의사결정을 도와야 합니다. 제공된 데이터를 분석하여 가장 가치 있는 고객을 찾아주세요!   

**요구사항**
1. 각 고객(UserID)별 총 구매 금액(Total)을 계산하세요.
   - 총 구매 금액은 개별 주문의 Price와 Quantity를 곱한 값들의 총합입니다.
2. 총 구매 금액이 가장 높은 상위 2명의 고객을 찾아, UserID와 총 구매 금액을 출력하세요.
3. 최종 결과는 총 구매 금액을 기준으로 내림차순으로 정렬하여 제시하세요.

In [2]:
# 1. 라이브러리 참조
from jussam import load_data
from pandas import cut, DataFrame
import numpy as np

# 2. 데이터 불러오기
sales = load_data('online_shop_sales')

# 3. 고객별 총 구매금액 계산
# Total = sales.groupby('UserID').apply(lambda x: (x.Price * x.Quantity).sum()).rename("Total")
# Total_df = DataFrame(Total)
sales2 = sales.copy()
sales2["Total"] = sales["Price"] * sales["Quantity"]
Total_df = sales2.filter(["UserID", "Total"]).groupby("UserID").sum()

Total_df

📚 우수 고객을 찾아라! - 영업 데이터 분석 챌린지

    field      description
--  ---------  ----------------
 0  OrderID    주문번호(인덱스)
 1  UserID     고객아이디
 2  Product    상품
 3  Price      가격
 4  Quantity   주문수량
 5  OrderDate  주문일

        Total
UserID
1001     1513
1002      205
1003     1000
1004     1550

In [74]:
Top2 = Total_df.sort_values('Total', ascending=False).head(2)
Top2

        Total
UserID
1004     1550
1001     1513